
/*******************************************************************************
 *  * JavaJACK - A JACK bridge for Java.
 *  *     Copyright (C) 2011  Chuck Ritola
 *  * 	chuck@ritolaaudio.com 
 * *	...with parts generated by JNAerator, where noted.
 *  * 
 *  *     This program is free software: you can redistribute it and/or modify
 *  *     it under the terms of the GNU General Public License as published by
 *  *     the Free Software Foundation, either version 3 of the License, or
 *  *     (at your option) any later version.
 *  * 
 *  *     This program is distributed in the hope that it will be useful,
 *  *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  *     GNU General Public License for more details.
 *  * 
 *  *     You should have received a copy of the GNU General Public License
 *  *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *  ******************************************************************************/
package com.ritolaaudio.jack;
import com.ochafik.lang.jnaerator.runtime.Structure;
/**
 * the new latency API operates on Ranges.<br>
 * <i>native declaration : ./jack/types.h:261</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class _jack_latency_range extends Structure<_jack_latency_range, _jack_latency_range.ByValue, _jack_latency_range.ByReference > {
	/// minimum latency
	public int min;
	/// maximum latency
	public int max;
	public _jack_latency_range() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"min", "max"});
	}
	/**
	 * @param min minimum latency<br>
	 * @param max maximum latency
	 */
	public _jack_latency_range(int min, int max) {
		super();
		this.min = min;
		this.max = max;
		initFieldOrder();
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected _jack_latency_range newInstance() { return new _jack_latency_range(); }
	public static _jack_latency_range[] newArray(int arrayLength) {
		return Structure.newArray(_jack_latency_range.class, arrayLength);
	}
	public static class ByReference extends _jack_latency_range implements Structure.ByReference {
		
	};
	public static class ByValue extends _jack_latency_range implements Structure.ByValue {
		
	};
}
